apiVersion: v1
kind: Pod
metadata:
  name: alpine-kubectl
  labels:
    owner: user-00.training.sass.ro
spec:
  containers:
  - name: alpine
    image: docker.io/bogd/alpine-kubectl
    stdin: true
    tty: true
