kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress
spec:
  podSelector:
    matchLabels: 
      role: management-ui
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: controller