apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-server
spec:
  replicas: 3
  selector:
    matchLabels:
      type: server
  template:
    metadata:
      labels:
        app: myapp
        type: server
    spec:
      containers:
      - name: webserver
        image: bogd/go-webserver:latest 
        