apiVersion: v1
kind: Pod
metadata:
  name: myapp-client
  labels:
    app: myapp
    type: client
spec:
  containers:
  - name: api-client
    image: bogd/alpine-tools:latest
    command:
    - /bin/bash
    - -c
    - echo -n "Getting data from API server... " && curl -s api-server:8000/hello && echo
  restartPolicy: Never
  initContainers:
  - name: wait-for-service
    image: bogd/alpine-tools:latest
    command:
    - /bin/bash
    - -c
    - until host api-server; do echo "Waiting for DNS..."; sleep 2; done
  - name: wait-for-api
    image: bogd/alpine-tools:latest
    command:
    - /bin/bash
    - -c
    - until curl -fs "http://api-server:8000/hello"; do echo "Waiting for API..."; sleep 2; done
    