apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      type: server
  template:
    metadata:
      labels:
        app: myapp
        type: server
    spec:
      containers:
      - name: webserver
        image: bogd/go-webserver-distroless:latest 
        env:
        - name: STUDENT_NAME
          value: Bogdan
