apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding-user-00
subjects:
- kind: ServiceAccount
  name: pod-viewer
  namespace: user-00
roleRef:
  kind: ClusterRole
  name: pod-reader-user-00
  apiGroup: rbac.authorization.k8s.io