apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:      
      containers:
      - name: gows
        image: bogd/go-webserver
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 300m
            memory: 64Mi
        env:
        - name: SECONDS_START_TO_HEALTHY
          value: "0"
        - name: SECONDS_HEALTHY_TO_READY
          value: "0" 
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
---
