apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
