apiVersion: batch/v1
kind: Job
metadata:
  name: siege
spec:
  template:
    spec:
      containers:
      - name: siege
        image: bogd/ubuntu-siege
        command: 
        - siege
        - --concurrent=5
        - --benchmark
        - --time=5m
        - http://webapp:8000
      restartPolicy: Never
  backoffLimit: 4

  