apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:      
      containers:
      - name: gows
        image: bogd/go-webserver
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 300m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 2
          failureThreshold: 2  
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          periodSeconds: 2
          failureThreshold: 2
        env:
        - name: SECONDS_START_TO_HEALTHY
          value: "0"
        - name: SECONDS_HEALTHY_TO_READY
          value: "0" 
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2
spec:
  selector:
    app: webapp2
  ports:
    - protocol: TCP
      port: 8000
---
